### ISSUE TITLE
Extra Alchemy

### ISSUE THREAD

**Issue by Andrew-Craig4** [FourInchKnife/Minecraft-Server-Modpack#10]
It adds new potion effects. It also adds new potion types (like stackable vials) The visibility effect is pretty overpowered, but it can be disabled in config. Also if you're testing this against other alchemy mods make sure to look at the rewind potion; it's the best potion type afaik.

https://www.curseforge.com/minecraft/mc-mods/extra-alchemy

**Comment by FourInchKnife** [comment]
Ok, so this mod is very different from the other alchemy mod I already have. I also really want this. Added!
