### ISSUE TITLE
[SUGGESTION] Artificial Foliage

### ISSUE THREAD

**Issue by Po-Taato** [FourInchKnife/Minecraft-Server-Modpack#11]
**Is your feature request related to an issue? Please describe.**
No

**Describe the mod you'd like to add or remove.**
Nice grass in ugly grass biome

**Add a link to the mod you want me to consider.**
https://www.curseforge.com/minecraft/mc-mods/artificial-foliage

**Comment by FourInchKnife** [comment]
I like this. Added!
