### ISSUE TITLE
Wither Totem

### ISSUE THREAD

**Issue by Andrew-Craig4** [FourInchKnife/Minecraft-Server-Modpack#17]
This mod is really cool. It adds a placeable totem that gives nearby mobs str II and speed I, but gives nearby players 2 levels of looting. It's designed to make mob grinding quicker, but harder. However, it also buffs mob farms.

https://www.curseforge.com/minecraft/mc-mods/wither-totem

**Comment by FourInchKnife** [comment]
Seems great, let me playtest it. I'll probably add it.

**Comment by FourInchKnife** [comment]
Added!
