### ISSUE TITLE
Wall jump mod

### ISSUE THREAD

**Issue by Andrew-Craig4** [FourInchKnife/Minecraft-Server-Modpack#2]
**Is your feature request related to an issue? Please describe.**
nope

**Describe the mod you'd like to add or remove.**
Wall jump mod

**Add a link to the mod you want me to consider.**
https://www.curseforge.com/minecraft/mc-mods/wall-jump-fabric

**Comment by Andrew-Craig4** [comment]
oh oops, this is a wall jump mod. Don't know if it's a good idea or not, but it looked pretty interesting

**Comment by FourInchKnife** [comment]
I was actually considering this exact mod. Glad to see some interest. I'll probably add it. Pleas also don't put links directly in the title because that messes with the way discord links to the github issue.

**Comment by FourInchKnife** [comment]
Alright, added! It seems like people don't think it's super OP because in end game you have elytra and mid game you have waystones.
