### ISSUE TITLE
Prefab Mod

### ISSUE THREAD

**Issue by Seabass138** [FourInchKnife/Minecraft-Server-Modpack#23]
Prefab is a collection of functional and aesthetic buildings that you can place into your world instantly. It's not cheap as you do have to gather lots of resources to place the buildings and make the blueprints. I think it would fun to use as it would make building large cities and bases easier and more fun. To make the blueprints all you have to do is gather large amounts of resources equivalent to the build you wish to make, then you can place the build wherever you want.

https://www.curseforge.com/minecraft/mc-mods/prefab-fabric

**Comment by FourInchKnife** [comment]
This doesn’t allow for custom buildings, so I think this would put a damper on creativity to some extent. I could add litematica though...

**Comment by Seabass138** [comment]
Yes the litematica mod would be awesom!
