### ISSUE TITLE
Custom Orb of Origins Crafting

### ISSUE THREAD

**Issue by FourInchKnife** [FourInchKnife/Minecraft-Server-Modpack#28]
At the moment there is no way to change your origin once you pick it. Should there be a way to?

**[VOTE](https://discord.com/channels/838160584687878195/838160584687878198/843557603875356685)**

**Comment by aw2p** [comment]
There really should be, but it should also be quite expensive right? Maybe a Wither star or something.

**Comment by FourInchKnife** [comment]
It will be craftable. the poll has decided that

**Comment by FourInchKnife** [comment]
idea:
```
NGN
GSG
NGN
```
N: netherite ingot 
G: enchanted golden apple
S: nether star

**Comment by Seabass138** [comment]
a nether star with 4 netherite ingots surrounding it
that's hard and pretty grindy to get

**Comment by FourInchKnife** [comment]
the thing is the orb is supposed to be VERY late game

**Comment by FourInchKnife** [comment]
actually good suggestion from me:
```
 T
NSN
 O
```
T: totem of undying
N: netherite
S: nether star
O: (requiem): opus daemonium

**Comment by Andrew-Craig4** [comment]
`NTN`
`USU`
`NEN`

N= netherite
T= trident
U= totem of undying
S= nether star
E=elytra

The point of this recipe is to force users to get materials from the nether, ocean, end, and pillagers. With Seabass's suggestion, you only need the nether which buffs nether based origins and nerfs ocean based origins.

**Comment by StayPos1tive** [comment]
I agree with Andrew, it should have items from all the dimensions.

**Comment by FourInchKnife** [comment]
i’m thinking this:
```
 AT
ANA
OA
```
A: aeternium ingots
T: totem of undying
N: nether star
O: opus daemonium

**Comment by FourInchKnife** [comment]
done
