### ISSUE TITLE
Enhanced Celestials Mod

### ISSUE THREAD

**Issue by Seabass138** [FourInchKnife/Minecraft-Server-Modpack#30]
Enhanced Celestials is a mod that aims to improve the overall environment of the night by adding lunar events such as Blood moons & Harvest moons. Blood moons increase mob spawn rates, and harvest moons increase crop output.

https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials-fabric

**Comment by FourInchKnife** [comment]
this may not work with sodium. if it does, i'll add it

please test

**Comment by Seabass138** [comment]
again i dont know how bro
