### ISSUE TITLE
Animal Feeding Trough Mod

### ISSUE THREAD

**Issue by Seabass138** [FourInchKnife/Minecraft-Server-Modpack#33]
Mobs that could be tempted will look for a feeding trough with their favorite food. A chicken will look for a feeding trough with seeds inside, a pig for carrots, and so on. Mobs will act as if the player feeds them, entering into love mode and eventually breeding.

https://www.curseforge.com/minecraft/mc-mods/animal-feeding-trough

**Comment by FourInchKnife** [comment]
so automatic mob breeding? seems interesting!

**Comment by FourInchKnife** [comment]
done
