### ISSUE TITLE
Dynamic Sound Filter

### ISSUE THREAD

**Issue by aw2p** [FourInchKnife/Minecraft-Server-Modpack#39]
### Checklist (put an X in each that apply):

- [x] This mod has a Fabric version
- [x] This mod is for MC 1.16.5 
- [x] This works with the latest version of the modpack
- [x] This is **NOT** blatantly overpowered
- [x] [The link below is **NOT** to a repost](https://stopmodreposts.org)

### Mod Description
Adds a few sound filters depending on your current location:

Reverb in caves and the nether
Muffled sounds when submerged in water or lava
Sounds become quieter when behind walls (Especially Wool or Sponge)
 

### Mod Page Link
https://www.curseforge.com/minecraft/mc-mods/dynamic-sound-filters

**Comment by FourInchKnife** [comment]
i meant to add this lol

i’ll add this and presence footsteps too

**Comment by FourInchKnife** [comment]
done
