### ISSUE TITLE
Illuminations 

### ISSUE THREAD

**Issue by aw2p** [FourInchKnife/Minecraft-Server-Modpack#40]
### Checklist (put an X in each that apply):

- [x] This mod has a Fabric version
- [x] This mod is for MC 1.16.5 
- [x] This works with the latest version of the modpack
- [x] This is **NOT** blatantly overpowered
- [x] [The link below is **NOT** to a repost](https://stopmodreposts.org)

### Mod Description
lluminations is a client-sided Minecraft Fabric mod that adds multiple ambient particles in order to make your world more enjoyable at night or in dark places, such as fireflies, glowworms and more!

### Mod Page Link
https://www.curseforge.com/minecraft/mc-mods/illuminations

**Comment by FourInchKnife** [comment]
done
