### ISSUE TITLE
Rubber trees extremely rare

### ISSUE THREAD

**Issue by Seabass138** [FourInchKnife/Minecraft-Server-Modpack#41]
ok so a problem I found with the mod pack is that rubber trees are incredibly rare

rubber is one of the base ingredients for most of the tech stuff in one of the industrial mods and it only spawns in a few vanilla biomes. Vanilla biomes are somewhat difficult to find on their own but then add the fact that the rubber tree might not even spawn in one rubber becomes an incredibly and unnecessarily hard to find resource.

if you could make them spawn in more than just vanilla biomes that would be great, if it's not possible oh well.

**Comment by FourInchKnife** [comment]
This isn’t a big issue. Rubber trees have saplings and are renewable.
