### ISSUE TITLE
Slimey Life

### ISSUE THREAD

**Issue by Andrew-Craig4** [FourInchKnife/Minecraft-Server-Modpack#6]
This mod is so dumb. You can make a slingshot thing that launches mobs away from you, or launches you away from blocks. There's also slime boots that have 130 durability and make you bounce on everything. It's a bit stupid, but it's so much fun to mess around with.

https://www.curseforge.com/minecraft/mc-mods/bouncy-life

**Comment by FourInchKnife** [comment]
I love this mod so much

**Comment by FourInchKnife** [comment]
I'm adding this
