### ISSUE TITLE
Medieval Weapons

### ISSUE THREAD

**Issue by Andrew-Craig4** [FourInchKnife/Minecraft-Server-Modpack#7]
Medieval weapons adds more weapon varieties to the game. I tested several of them and the mod seems pretty balanced. It really just adds optional variety for people when deciding what weapon to use.

https://www.curseforge.com/minecraft/mc-mods/medievalweapons

**Comment by FourInchKnife** [comment]
I *might* have this mod already. I *do* have very similar mods. I think I'm going to close this as "added" even though we don't have this exact mod.
