### ISSUE TITLE
No Wings

### ISSUE THREAD

**Issue by Andrew-Craig4** [FourInchKnife/Minecraft-Server-Modpack#9]
Cosmetic wing mods are cool, but any wing mod that buffs elytras would be ridiculously overpowered. Elytras are already far and above the best form of long or medium distance travel. Buffing them would be completely unneccisary.

**Comment by FourInchKnife** [comment]
wings stay. check discord.

**Comment by FourInchKnife** [comment]
turns out wings from the winged mod aren't even that end game. i'll remove it.
